### ISSUE TITLE
Mesh with mixed element types cannot be converted

### ISSUE THREAD

**Issue by ywan459** [calculix/unv2ccx#2]
Hi there, 

The converter has an issue that cannot convert the mesh with multi-types of elements. If a UNV file contains the beam elements and solid elements,  as an example, the converter would produce nothing. I have attahced an example unv file.

I am wondering whether the convert can proceed the multi-type of elements model. Thanks!

Regards
ywan459
[Compound_Mesh_1.zip](https://github.com/calculix/unv2ccx/files/5141457/Compound_Mesh_1.zip)

**Comment by imirzov** [comment]
Thank you for testing the converter. I'll have a look and fix it next week.

**Comment by imirzov** [comment]
Ok, I've checked your model. Converter works fine:
![Compound_Mesh_1](https://user-images.githubusercontent.com/4652710/91654363-6057e600-eaa8-11ea-912e-60427a3b63ee.png)

[Compound_Mesh_1_inp.zip](https://github.com/calculix/unv2ccx/files/5146481/Compound_Mesh_1_inp.zip)

**Comment by ywan459** [comment]
Hi, 

Yes you are right, it works. Sorry I was confused by myself with the UNV converters of launcher-CalculiX 3.4. 

Regards
Yikun Wang
